### ISSUE TITLE
大佬这个东西怎么用啊

### ISSUE THREAD

**Issue by yuban01652** [pasiiww/gf_theater_predict#1]
大佬，咱是完全没接触过深度学习，也是第一次看python代码的小白，稍有兴趣跑了一下，咱猜可能是在data里填数据，然后在model*.py里的train那部分改个循环数，然后等模型训练收敛？但为啥咱看到test_loss已经挺小的了，但和大佬的预测数值差距挺大的呢，还要调什么东西嘛（趴）。
当然咱只是有点兴趣，大佬要是觉得说起来很麻烦的话可以不用管咱（趴），毕竟大佬自己生活要紧啊。

**Comment by pasiiww** [comment]
抱歉现在才看到issue（

你的做法应该是没问题的。最好先把旧的模型文件删除掉再重新训练，不然训练结果会跑偏
一般来说循环10000次，test loss在0.1左右的时候就可以了，结果会有几个点的误差，5%以内的浮动都是正常的

**Comment by yuban01652** [comment]
ok，谢谢大佬，咱再试试（趴）
